# Makefile automatically generated by ghdl
# Version: GHDL 0.36 (tarball) [Dunoon edition] - llvm code generator
# Command used to generate this makefile:
# ghdl --gen-makefile --workdir=simu --work=work uni_bin_ctr_test

GHDL=ghdl
GHDLFLAGS= --workdir=simu --work=work

# Default target
all: uni_bin_ctr_test

# Elaboration target
uni_bin_ctr_test: /Users/biplavkarna/mydocs/ghdl-0.36-macosx-llvm/lib/ghdl/ieee/v93/std_logic_1164.o /Users/biplavkarna/mydocs/ghdl-0.36-macosx-llvm/lib/ghdl/ieee/v93/std_logic_1164_body.o /Users/biplavkarna/mydocs/ghdl-0.36-macosx-llvm/lib/ghdl/ieee/v93/numeric_std.o /Users/biplavkarna/mydocs/ghdl-0.36-macosx-llvm/lib/ghdl/ieee/v93/numeric_std-body.o simu/universal_binary_counter_test.o simu/universal_binary_counter.o
	$(GHDL) -e $(GHDLFLAGS) $@

# Run target
run: uni_bin_ctr_test
	$(GHDL) -r uni_bin_ctr_test $(GHDLRUNFLAGS) --stop-time=1000ns --vcd=out.vcd

# Targets to analyze files
/Users/biplavkarna/mydocs/ghdl-0.36-macosx-llvm/lib/ghdl/ieee/v93/std_logic_1164.o: /Users/biplavkarna/mydocs/ghdl-0.36-macosx-llvm/lib/ghdl/ieee/v93/../../src/ieee/std_logic_1164.v93
	@echo "This file was not locally built ($<)"
	exit 1
/Users/biplavkarna/mydocs/ghdl-0.36-macosx-llvm/lib/ghdl/ieee/v93/std_logic_1164_body.o: /Users/biplavkarna/mydocs/ghdl-0.36-macosx-llvm/lib/ghdl/ieee/v93/../../src/ieee/std_logic_1164_body.v93
	@echo "This file was not locally built ($<)"
	exit 1
/Users/biplavkarna/mydocs/ghdl-0.36-macosx-llvm/lib/ghdl/ieee/v93/numeric_std.o: /Users/biplavkarna/mydocs/ghdl-0.36-macosx-llvm/lib/ghdl/ieee/v93/../../src/ieee/numeric_std.v93
	@echo "This file was not locally built ($<)"
	exit 1
/Users/biplavkarna/mydocs/ghdl-0.36-macosx-llvm/lib/ghdl/ieee/v93/numeric_std-body.o: /Users/biplavkarna/mydocs/ghdl-0.36-macosx-llvm/lib/ghdl/ieee/v93/../../src/ieee/numeric_std-body.v93
	@echo "This file was not locally built ($<)"
	exit 1
simu/universal_binary_counter_test.o: testbench/universal_binary_counter_test.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
simu/universal_binary_counter.o: src/universal_binary_counter.vhd
	$(GHDL) -a $(GHDLFLAGS) $<

# Files dependences
/Users/biplavkarna/mydocs/ghdl-0.36-macosx-llvm/lib/ghdl/ieee/v93/std_logic_1164.o: 
/Users/biplavkarna/mydocs/ghdl-0.36-macosx-llvm/lib/ghdl/ieee/v93/std_logic_1164_body.o:  /Users/biplavkarna/mydocs/ghdl-0.36-macosx-llvm/lib/ghdl/ieee/v93/std_logic_1164.o
/Users/biplavkarna/mydocs/ghdl-0.36-macosx-llvm/lib/ghdl/ieee/v93/numeric_std.o:  /Users/biplavkarna/mydocs/ghdl-0.36-macosx-llvm/lib/ghdl/ieee/v93/std_logic_1164.o
/Users/biplavkarna/mydocs/ghdl-0.36-macosx-llvm/lib/ghdl/ieee/v93/numeric_std-body.o:  /Users/biplavkarna/mydocs/ghdl-0.36-macosx-llvm/lib/ghdl/ieee/v93/numeric_std.o
simu/universal_binary_counter_test.o:  /Users/biplavkarna/mydocs/ghdl-0.36-macosx-llvm/lib/ghdl/ieee/v93/std_logic_1164.o /Users/biplavkarna/mydocs/ghdl-0.36-macosx-llvm/lib/ghdl/ieee/v93/std_logic_1164_body.o /Users/biplavkarna/mydocs/ghdl-0.36-macosx-llvm/lib/ghdl/ieee/v93/numeric_std.o /Users/biplavkarna/mydocs/ghdl-0.36-macosx-llvm/lib/ghdl/ieee/v93/numeric_std-body.o
simu/universal_binary_counter.o:  /Users/biplavkarna/mydocs/ghdl-0.36-macosx-llvm/lib/ghdl/ieee/v93/std_logic_1164.o /Users/biplavkarna/mydocs/ghdl-0.36-macosx-llvm/lib/ghdl/ieee/v93/numeric_std.o
